# Generated by Django 5.0.1 on 2024-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='player',
            field=models.CharField(default='', max_length=1),
        ),
    ]
