# Generated by Django 5.0.1 on 2024-03-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bid_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
