# Generated by Django 5.0.1 on 2024-02-02 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=4)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.CharField(max_length=16)),
                ('w', models.CharField(max_length=16)),
                ('player', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BidClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField()),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_ancestor', to='api.bid')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_descendants', to='api.bid')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='api.deal'),
        ),
    ]
