# Generated by Django 5.0.1 on 2024-02-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='comment',
            field=models.TextField(default='', max_length=100),
        ),
    ]
